version: '2.4'
services:
  app:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile.devcontainer
    volumes:
      - devcontainer-python-bashhistory:/commandhistory:z
      - ${localWorkspaceFolder}:/workspaces/${localWorkspaceFolderBasename}:z
    env_file:
      - dev.env
      - .devcontainer/devcontainer.env
